### ISSUE TITLE
タイムテーブルのREADMの文章修正したので置き換えお願いします笑

### ISSUE THREAD

**Issue by Ayakie** [sasakiK/dash_hands_on#6]
|---|

| 16:15 ~16:25 | タイトルとアップロードの部分だけ作って、cssでいい感じに表示させてみる |
| 16:25 ~ 16:40 | 単純な線形モデルを作り、残渣プロットとスコアを表示させる |
| 16:40 ~ 16:55 | モデルを選択するドロップダウンを作って、選択したモデルに応じて出力結果が変わるような動的なページを作る |
| 16:55 ~ 17:10 | ファイルをアップロードし、データフレームとして表示させる (アップロードとデータの学習は別々で行う) |
| 17:10 ~ 17:25 | 読み込んだデータをtrainデータとして読み込むように連携(Callback)させる |

**Comment by sasakiK** [comment]
|名前|内容|
|:---|:---|
| 16:15~16:25 | タイトルとアップロードの部分だけ作って、cssでいい感じに表示させてみる |
| 16:25~16:40 | 単純な線形モデルを作り、残渣プロットとスコアを表示させる |
| 16:40~16:55 | モデルを選択するドロップダウンを作って、選択したモデルに応じて出力結果が変わるような動的なページを作る |
| 16:55~17:10 | ファイルをアップロードし、データフレームとして表示させる (アップロードとデータの学習は別々で行う) |
| 17:10~17:25 | 読み込んだデータをtrainデータとして読み込むように連携(Callback)させる |

**Comment by sasakiK** [comment]
なおった〜
